def help_cmd(): # help list
    print("="*10 + "BASE CMDS" + "="*10)
    print("shutdown ---> off system.")
    print("help ---> this command, list of commands.")
    print("chost ---> change hostname.")
    print("echo ---> displays text on the screen, echo hello, world!")
    print("pwd, whereami ---> displays where you are.")
    print("whoami ---> displays current user.")
    print("version ---> displays the system version.")
    print("ls ---> list of files or dirs in dir, where is an user.")
    print("cd ---> change directory.")
    print("date ---> displays current date.")
    print("time ---> displays current time.")
    print("clear ---> clears terminal.")
    print("cat ---> displays text from file.")
    print("calendar ---> a beautiful calendar with the year and month of your choice")
        
    print("="*10 + "APPS" + "="*10 )
    print("slowfetch ---> fastfetch analog.")
    #print("startde ---> start DE (de is not completed)")
