def help_cmd(): # help list
    print("="*10 + "BASE CMDS" + "="*10)
    print("="*5+"Work with Files/Dirs/Path"+"="*5)
    print("ls ---> list of files or dirs in dir, where is an user. flags: -t ---> shows the last modification time (on Unix-like systems)")
    print("cd ---> change directory.")
    print("rm ---> removes a file or directory. rm test/rm test.py/rm ../test/test.txt")
    print("touch ---> create new file.") #change file timestamps or
    print("cat ---> displays text from file.")
    print("echo ---> displays text on the screen, echo hello, world! Or, writes text to a file. echo print('hello world') > filename.py. ATTENTION! This command will completely overwrite the file.")
    print("pwd, whereami ---> displays where you are.")

    print("="*5+"Work with users"+"="*5)
    print("su ---> logs into another user on your PC")
    print("whoami ---> displays current user.")

    print("="*5+"etc"+"="*5)
    print("shutdown ---> off system.")
    print("help ---> this command, list of commands.")
    print("chost ---> change hostname.")
    print("version ---> displays the system version.")
    print("date ---> displays current date.")
    print("time ---> displays current time.")
    print("clear ---> clears terminal.")
    print("calendar ---> a beautiful calendar with the year and month of your choice")
    print("history --> view the history list")
    print("clear_history --> clear the history list")

    print("="*10 + "APPS" + "="*10 )
    print("quick - Package manager. Flags - -S (install), -s --search (search) -R (remove)")
    print("slowfetch ---> fastfetch analog.")
